-- 00-init.sql: Configuración Inicial de Base de Datos y Usuarios

-- 1. Asegurar usuarios y roles críticos de Supabase
DO
$do$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'supabase_admin') THEN
      CREATE ROLE supabase_admin WITH LOGIN PASSWORD 'postgres-password-12345' SUPERUSER CREATEDB CREATEROLE REPLICATION;
   ELSE
      ALTER ROLE supabase_admin WITH LOGIN PASSWORD 'postgres-password-12345' SUPERUSER CREATEDB CREATEROLE REPLICATION;
   END IF;
END
$do$;

DO
$do$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'anon') THEN
      CREATE ROLE anon NOLOGIN;
   END IF;
   
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'authenticated') THEN
      CREATE ROLE authenticated NOLOGIN;
   END IF;
   
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'service_role') THEN
      CREATE ROLE service_role NOLOGIN;
   END IF;
END
$do$;

GRANT anon TO postgres;
GRANT authenticated TO postgres;
GRANT service_role TO postgres;
GRANT anon TO supabase_admin;
GRANT authenticated TO supabase_admin;
GRANT service_role TO supabase_admin;

-- 2. Esquema de la Aplicación (Copiado de db_schema.sql)

-- TABLA PROYECTOS (BODAS)
create table if not exists projects (
  id text primary key,
  bride_name text,
  groom_name text,
  couple_name text,
  wedding_date text,
  venue text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- TABLA MESAS
create table if not exists tables (
  id text primary key,
  project_id text references projects(id) on delete cascade,
  name text,
  capacity int,
  created_at timestamptz default now()
);

-- TABLA INVITADOS (GUESTS)
create table if not exists guests (
  id text primary key,
  project_id text references projects(id) on delete cascade,
  first_name text,
  last_name text,
  email text,
  phone text,
  guests_confirmed int,
  rsvp_status text,
  dietary text,
  sub_guests jsonb,
  created_at timestamptz default now()
);

-- TABLA ASIGNACIONES (ASSIGNMENTS)
create table if not exists assignments (
  id text primary key,
  project_id text references projects(id) on delete cascade,
  table_id text references tables(id) on delete cascade,
  rsvp_id text references guests(id) on delete cascade,
  sub_guest_idx int,
  created_at timestamptz default now()
);

-- TABLA LOGS
create table if not exists login_logs (
  id bigint generated by default as identity primary key,
  project_id text,
  couple_name text,
  timestamp timestamptz default now()
);

-- POLÍTICAS DE SEGURIDAD (RLS)
alter table projects enable row level security;
alter table tables enable row level security;
alter table guests enable row level security;
alter table assignments enable row level security;
alter table login_logs enable row level security;

create policy "Enable all access for anon" on projects for all using (true) with check (true);
create policy "Enable all access for anon" on tables for all using (true) with check (true);
create policy "Enable all access for anon" on guests for all using (true) with check (true);
create policy "Enable all access for anon" on assignments for all using (true) with check (true);
create policy "Enable all access for anon" on login_logs for all using (true) with check (true);

-- Permisos para roles (Crucial)
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
