-- TABLA PROYECTOS (BODAS)
create table if not exists projects (
  id text primary key,
  bride_name text,
  groom_name text,
  couple_name text,
  wedding_date text,
  venue text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- TABLA MESAS
create table if not exists tables (
  id text primary key,
  project_id text references projects(id) on delete cascade,
  name text,
  capacity int,
  created_at timestamptz default now()
);

-- TABLA INVITADOS (GUESTS)
-- Guardamos sub_guests como JSONB para mantener la compatibilidad con tu lógica actual (arrays)
create table if not exists guests (
  id text primary key,
  project_id text references projects(id) on delete cascade,
  first_name text,
  last_name text,
  email text,
  phone text,
  guests_confirmed int, -- Cantidad total de cupos
  rsvp_status text,
  dietary text,
  sub_guests jsonb, -- Aquí guardamos el array de integrantes
  created_at timestamptz default now()
);

-- TABLA ASIGNACIONES (ASSIGNMENTS)
create table if not exists assignments (
  id text primary key,
  project_id text references projects(id) on delete cascade,
  table_id text references tables(id) on delete cascade,
  rsvp_id text references guests(id) on delete cascade,
  sub_guest_idx int,
  created_at timestamptz default now()
);

-- TABLA LOGS
create table if not exists login_logs (
  id bigint generated by default as identity primary key,
  project_id text,
  couple_name text,
  timestamp timestamptz default now()
);

-- POLÍTICAS DE SEGURIDAD (ROW LEVEL SECURITY)
-- Para simplificar en este paso, habilitaremos acceso público anonimo para leer/escribir
-- IMPORTANTE: En producción real deberías restringir esto, pero para tu VPS privado está bien por ahora.
alter table projects enable row level security;
alter table tables enable row level security;
alter table guests enable row level security;
alter table assignments enable row level security;
alter table login_logs enable row level security;

create policy "Enable all access for anon" on projects for all using (true) with check (true);
create policy "Enable all access for anon" on tables for all using (true) with check (true);
create policy "Enable all access for anon" on guests for all using (true) with check (true);
create policy "Enable all access for anon" on assignments for all using (true) with check (true);
create policy "Enable all access for anon" on login_logs for all using (true) with check (true);
