server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index login.html index.html; # Definimos login.html como la página por defecto si index.html no existe

    location / {
        try_files $uri $uri/ /login.html;
    }

    # Configuración de caché para archivos estáticos comunes
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
