-- Reemplazo COMPLETO de la tabla providers con la lista revisada por la dueña (177 proveedores).
-- Ejecutar en el SQL Editor de Supabase. Esto BORRA todos los proveedores actuales y los reemplaza.
-- El historial de solicitudes (budget_requests_log) queda igual, pero pierde su vínculo con
-- proveedores que ya no estén en la lista nueva (por el ON DELETE CASCADE de la FK a providers).

delete from providers;

insert into providers (name, category, emails, is_active)
values
  ('Estancia Ricardo Francisco', 'Venue (Estancia)', ARRAY['estanciaricardofrancisco@gmail.com']::text[], true),
  ('Hostería El Cazador', 'Venue (Hostería)', ARRAY['info@hosteriaelcazador.com']::text[], true),
  ('Dique Loreto', 'Venue (Salón)', ARRAY['islaverde644@gmail.com']::text[], true),
  ('El Abierto', 'Venue (Salón)', ARRAY['pedro@mezclaeventos.com']::text[], true),
  ('Darwin Tortugas', 'Venue (Salón)', ARRAY['tortugas@somosdarwin.com.ar']::text[], true),
  ('Darwin Buen Ayre', 'Venue (Salón)', ARRAY['buenayre@somosdarwin.com.ar']::text[], true),
  ('Estancia El Recuerdo', 'Venue (Estancia)', ARRAY['consultas@estanciaelrecuerdo.com']::text[], true),
  ('Estancia Santa Elena', 'Venue (Estancia)', ARRAY['info@santaelenaeventos.com.ar']::text[], true),
  ('5500 Figueroa', 'Venue (Salón)', ARRAY['eventos@5500figueroa.com.ar']::text[], true),
  ('Palacio Sans Souci', 'Venue (Salón)', ARRAY['marinablanco@palaciosanssouci.com']::text[], true),
  ('Quinta de Anchorena', 'Venue (Quinta)', ARRAY['nuva@nuvacatering.com']::text[], true),
  ('Quinta de Bellavista', 'Venue (Quinta)', ARRAY['ventas@laquintabellavista.com.ar']::text[], true),
  ('Espacio Pilar', 'Venue (Salón)', ARRAY['sociales@espaciopilar.com.ar']::text[], true),
  ('Espacio Márquez', 'Venue (Salón)', ARRAY['sociales@espaciomarquez.com.ar']::text[], true),
  ('Estancia Benquerencia', 'Venue (Estancia)', ARRAY['diego.natale@benquerencia.com.ar']::text[], true),
  ('La Reserva', 'Venue (Club de Playa)', ARRAY['victoria.pinella@lareservaplaya.com']::text[], true),
  ('Yatch PMO', 'Venue (Salón)', ARRAY['planner@ycpm.info']::text[], true),
  ('AAPolo', 'Venue (Salón)', ARRAY['lorena@aapoloeventos.com']::text[], true),
  ('Club Hípico Argentino', 'Venue (Salón)', ARRAY['info@hipicoargentinoeventos.com.ar']::text[], true),
  ('Espacio Tigre', 'Venue (Salón)', ARRAY['sociales@espaciotigre.com.ar']::text[], true),
  ('Torreon del Monje', 'Venue (Salón)', ARRAY['eventos@torreondelmonjemdp.com']::text[], true),
  ('Mar Eventos', 'Venue (Salón)', ARRAY['info@mareventos.com.ar']::text[], true),
  ('Cabo Largo', 'Venue (Playas)', ARRAY['eventos@cabolargo.com.ar']::text[], true),
  ('Playa Luna Roja', 'Venue (Club de Playa)', ARRAY['comercial@playalunaroja.com']::text[], true),
  ('Maal Wines', 'Venue (Bodega)', ARRAY['gbiondo@maalwines.com']::text[], true),
  ('Penedo Borges', 'Venue (Bodega)', ARRAY['eventos@penedoborges.com']::text[], true),
  ('Bombal', 'Venue (Bodega)', ARRAY['info@bodegabombal.com']::text[], true),
  ('La Morada', 'Venue (Alojamiento / Salón)', ARRAY['nayla@resolve.net.ar']::text[], true),
  ('Huentala Wines', 'Venue (Bodega)', ARRAY['eventos@huentalawines.com']::text[], true),
  ('Durigutti', 'Venue (Bodega)', ARRAY['turismo@durigutti.com']::text[], true),
  ('Piso Tres', 'Venue (Salón)', ARRAY['pedro@mezclaeventos.com']::text[], true),
  ('La Escondida Olivos', 'Venue (Salón)', ARRAY['maria@galindez.com.ar']::text[], true),
  ('Bamba', 'Ambientación', ARRAY['vero@bambaambientaciones.com.ar', 'gime@bambaambientaciones.com.ar']::text[], true),
  ('Luminis', 'Ambientación', ARRAY['luminisambientacion@gmail.com']::text[], true),
  ('Dicha', 'Ambientación', ARRAY['contacto@dichambientacion.com']::text[], true),
  ('Magnolia', 'Ambientación', ARRAY['ambientacionesmagnolia@gmail.com']::text[], true),
  ('Chic to chic', 'Ambientación', ARRAY['info@chictochicambientaciones.com']::text[], true),
  ('Genoveva Eventos', 'Ambientación', ARRAY['soniamorik@gmail.com']::text[], true),
  ('Be', 'Ambientación', ARRAY['info@beambientaciones.com']::text[], true),
  ('Amasb', 'Ambientación', ARRAY['luz@amasb.com.ar', 'clara@amasb.com.ar']::text[], true),
  ('Cata Gallo', 'Ambientación', ARRAY['info@catagallo.com.ar']::text[], true),
  ('Mercedes Courrage', 'Ambientación', ARRAY['mercedes@mercedescourreges.com.ar', 'martina@mercedescourreges.com.ar', 'catalina@mercedescourreges.com.ar']::text[], true),
  ('Hermanas Carandoti', 'Ambientación', ARRAY['cande@hermanascaradonti.com', 'lola@hermanascaradonti.com']::text[], true),
  ('By Felicity', 'Ambientación', ARRAY['agus.byfelicity@gmail.com', 'info.byfelicity@gmail.com']::text[], true),
  ('Felicidad Rodante', 'Ambientación', ARRAY['produccion@felicidadrodante.com', 'virasseff@felicidadrodante.com', 'quiero@felicidadrodante.com']::text[], true),
  ('Ambient Chic', 'Ambientación', ARRAY['info@ambientchic.com.ar']::text[], true),
  ('Bar de eventos (BDE)', 'Barra', ARRAY['hola@bardeeventos.com', 'administracion@bardeeventos.com', 'logistica@bardeeventos.com']::text[], true),
  ('Ehningen', 'Barra', ARRAY['info@barraparaeventos.com.ar']::text[], true),
  ('CZ', 'Barra', ARRAY['info@czdrinks.com.ar']::text[], true),
  ('Ramiro Ferreri (RF)', 'Barra', ARRAY['yo@ramiroferreri.com', 'ramiroferreri@gmail.com', 'rfpresupuestos1@gmail.com']::text[], true),
  ('Holy', 'Barra', ARRAY['info@holychampagne.com.ar']::text[], true),
  ('Tomate algo', 'Barra', ARRAY['info@tomatealgo.com.ar']::text[], true),
  ('T-bar', 'Barra', ARRAY['hola@t-bar.com.ar']::text[], true),
  ('Dream Factory / Drink Factory', 'Barra', ARRAY['info@drinkfactory.com.ar']::text[], true),
  ('Fashion Drinks', 'Barra', ARRAY['info@fashiondrinks.com']::text[], true),
  ('Julep de Inés de los Santos', 'Barra', ARRAY['info@julep.com.ar']::text[], true),
  ('Softies', 'Catering', ARRAY['maria.fazzato@softiescatering.com']::text[], true),
  ('Malcolm', 'Catering', ARRAY['info@malcolmcatering.com.ar']::text[], true),
  ('Brazzi', 'Catering', ARRAY['info@brazzicatering.com.ar']::text[], true),
  ('Fava', 'Catering', ARRAY['info@favacatering.com.ar', 'eugenia@favacatering.com.ar']::text[], true),
  ('Expertos asadores', 'Catering', ARRAY['Info@expertosasadores.com.ar']::text[], true),
  ('Galindez', 'Catering', ARRAY['maria@galindez.com.ar']::text[], true),
  ('Guillen', 'Catering', ARRAY['eventos@guillencatering.com.ar']::text[], true),
  ('Schuster', 'Catering', ARRAY['noelia.arbo@schuster-catering.com', 'nicolas.d@schuster-catering.com', 'info@schuster-catering.com']::text[], true),
  ('Teist', 'Catering', ARRAY['ignacio@teist.com.ar']::text[], true),
  ('Echague', 'Catering', ARRAY['mariaechaguecatering@gmail.com']::text[], true),
  ('Tarelas', 'Catering', ARRAY['info@tarelas.com.ar']::text[], true),
  ('Vivanco', 'Catering', ARRAY['ventas@vivanco.com.ar']::text[], true),
  ('PCM', 'Catering', ARRAY['contacto@paracomertemejor.com.ar']::text[], true),
  ('Quebracho y hierro', 'Catering', ARRAY['quebracho.hierro@gmail.com']::text[], true),
  ('Art Catering', 'Catering', ARRAY['artventas@art-catering.com.ar']::text[], true),
  ('Kiria Catering', 'Catering', ARRAY['info@kiria.com.ar']::text[], true),
  ('Eat Catering', 'Catering', ARRAY['elena@eatcatering.com.ar', 'info@eatcatering.com.ar']::text[], true),
  ('Los Petersen', 'Catering', ARRAY['catering@lospetersen.com']::text[], true),
  ('Sucath David Catering', 'Catering', ARRAY['eventos@sucathdavid.com']::text[], true),
  ('Griss', 'Técnica / DJ', ARRAY['info@griss.com.ar']::text[], true),
  ('Camisani', 'Técnica / DJ', ARRAY['camisani.music@gmail.com', 'nicolas@camisani.com.ar']::text[], true),
  ('Black Murray Smith', 'Técnica / DJ', ARRAY['tomas@murrayblacksmith.com']::text[], true),
  ('Sarapura', 'Técnica / DJ', ARRAY['paula.gallardo@gruposarapura.com.ar', 'hola@gruposarapura.com.ar', 'flopyperego@sarapura.com']::text[], true),
  ('Repila', 'Técnica / DJ', ARRAY['sebamaidana@repila.com.ar', 'joseluis@repila.com.ar']::text[], true),
  ('Juli Urristi', 'Técnica / DJ', ARRAY['Juliurristidjs@gmail.com']::text[], true),
  ('Trueba', 'Técnica / DJ', ARRAY['eduardo@truebagroup.net', 'german@truebagroup.net']::text[], true),
  ('Vidal Campos', 'Técnica / DJ', ARRAY['comercial@vidalcampos.com.ar']::text[], true),
  ('TM', 'Técnica / DJ', ARRAY['bernardita@tmdj.com.ar']::text[], true),
  ('Alejandro Massey', 'Técnica / DJ', ARRAY['info@masseymusic.com.ar']::text[], true),
  ('Leo Cragno', 'Técnica / DJ', ARRAY['info@leocragno.com.ar']::text[], true),
  ('Agus Faita', 'Maquillaje / Peinado', ARRAY['agus.faita@gmail.com']::text[], true),
  ('Yami La Coquette', 'Maquillaje / Peinado', ARRAY['info@lacoquettenovias.com']::text[], true),
  ('La China Buenos Aires', 'Maquillaje / Peinado', ARRAY['lachinabsas@gmail.com']::text[], true),
  ('Mar make up', 'Maquillaje / Peinado', ARRAY['marmakeuphair@gmail.com']::text[], true),
  ('Kari Loggia', 'Maquillaje / Peinado', ARRAY['karina.loggia@gmail.com']::text[], true),
  ('Vero Fox', 'Maquillaje / Peinado', ARRAY['verofoxmakeup@gmail.com']::text[], true),
  ('Luli Ruiz', 'Maquillaje / Peinado', ARRAY['luliruiz44@gmail.com']::text[], true),
  ('Estudio Frumboli', 'Maquillaje / Peinado', ARRAY['estudio@bettinafrumboli.com']::text[], true),
  ('Celeste Uria', 'Maquillaje / Peinado', ARRAY['CelesteUriaEstudio@gmail.com']::text[], true),
  ('Laura Pintado', 'Maquillaje / Peinado', ARRAY['laupintadomakeup@gmail.com']::text[], true),
  ('Paula Saez', 'Maquillaje / Peinado', ARRAY['paulasaezmakeup@gmail.com']::text[], true),
  ('Rock That Makeup', 'Maquillaje / Peinado', ARRAY['mpaulicontreras@gmail.com']::text[], true),
  ('Celeste Moreyra', 'Maquillaje / Peinado', ARRAY['mariaceleste.hairboutique@gmail.com']::text[], true),
  ('Todaro - Dianez', 'Foto y video', ARRAY['info@lucastodaro.com.ar', 'germandianez@gmail.com']::text[], true),
  ('Dream Big', 'Foto y video', ARRAY['contacto@dreambigestudio.com']::text[], true),
  ('Alejandro Trotta', 'Video', ARRAY['aletrottavideografo@gmail.com']::text[], true),
  ('Norman Parunov', 'Foto y video', ARRAY['info@parunov.com.ar']::text[], true),
  ('Pixel / Pixel Produxiones', 'Foto y video', ARRAY['pixelProduxiones@hotmail.com']::text[], true),
  ('Emi Gualdoni', 'Foto', ARRAY['info@emiliagualdoni.com']::text[], true),
  ('Filmyco', 'Foto y video', ARRAY['info@filmyco.com']::text[], true),
  ('Nico Panunnzio', 'Foto y video', ARRAY['info@nicolaspannunzio.com.ar']::text[], true),
  ('Bleu', 'Foto y video', ARRAY['info@bleuestudio.com']::text[], true),
  ('Mariano Brusa', 'Foto y video', ARRAY['marianobrusa@marianobrusa.com.ar']::text[], true),
  ('Pogo', 'Foto y video', ARRAY['hola@pogoeventos.com']::text[], true),
  ('Fede Petri', 'Foto', ARRAY['info@fedepetri.com']::text[], true),
  ('Finales Felices', 'Video', ARRAY['holafinalesfelices@gmail.com']::text[], true),
  ('Paula Barcia', 'Foto', ARRAY['info@paulacia.com']::text[], true),
  ('Javier Belli', 'Video', ARRAY['belli_javier@hotmail.com']::text[], true),
  ('Facundo Corral', 'Video', ARRAY['facundoncorral@gmail.com']::text[], true),
  ('Gonzales Blanc', 'Foto y video', ARRAY['estudiogonzalezblanc@gmail.com']::text[], true),
  ('Punto Avi', 'Foto y video', ARRAY['fabian@puntoavi.com.ar', 'info@punto-avi.com.ar']::text[], true),
  ('Estudio ¾', 'Foto y video', ARRAY['info@estudiotrescuartos.com.ar']::text[], true),
  ('Estudio V', 'Foto y video', ARRAY['hola@estudiov.net']::text[], true),
  ('Alro Producciones', 'Foto y video', ARRAY['info@alro.com.ar']::text[], true),
  ('Hobby Estudio Creativo', 'Foto y video', ARRAY['infocapital@hobbystudiocreativo.com', 'info@hobbystudio.com']::text[], true),
  ('La ceremonia', 'Ceremonia', ARRAY['laceremoniareuniones@gmail.com']::text[], true),
  ('Arturo', 'Ceremonia', ARRAY['estudiobayala@hotmail.com']::text[], true),
  ('Tu ceremonia', 'Ceremonia', ARRAY['contacto@tuceremonia.com']::text[], true),
  ('Bodas para el alma', 'Ceremonia', ARRAY['bodasparalasalmas@gmail.com']::text[], true),
  ('Charlie', 'Ceremonia', ARRAY['tuoficiantedeceremonias@gmail.com']::text[], true),
  ('Leandro Biasutto', 'Ceremonia (Juez de paz)', ARRAY['leobiasutto@gmail.com']::text[], true),
  ('Fabian Skornik', 'Ceremonia (Rabino)', ARRAY['agustina@lamroth.org']::text[], true),
  ('El Show de Andy', 'Shows', ARRAY['elshowdeandy@hotmail.com']::text[], true),
  ('Sin Ensayo', 'Shows', ARRAY['SINENSAYO@hotmail.com.ar']::text[], true),
  ('Cafecitos', 'Shows', ARRAY['veronica.cgastaldiproducciones@gmail.com']::text[], true),
  ('China Mora', 'Shows', ARRAY['veronica.cgastaldiproducciones@gmail.com']::text[], true),
  ('Bairez Jazz Quartet', 'Shows', ARRAY['bairesjazzquartet@gmail.com']::text[], true),
  ('Cuerdas del Sur', 'Shows', ARRAY['cuerdasdelsureventos@gmail.com']::text[], true),
  ('LNA', 'Shows', ARRAY['info@lnaeventos.com.ar']::text[], true),
  ('Morris Brown', 'Shows', ARRAY['morris_brown6@hotmail.com']::text[], true),
  ('Nina Vais', 'Shows', ARRAY['info@ninavais.com']::text[], true),
  ('Fernando saxo', 'Shows', ARRAY['showdesaxo@hotmail.com']::text[], true),
  ('Soy el violinista', 'Shows', ARRAY['soyelviolinista@gmail.com']::text[], true),
  ('El beso del arbol', 'Shows', ARRAY['fedelbehnson@gmail.com']::text[], true),
  ('Lets Party', 'Extras (Glitter / Cotillón)', ARRAY['hola@letspartyarg.com', 'letspartyarg@gmail.com']::text[], true),
  ('Estacion Glam', 'Extras (Glitter)', ARRAY['estacionesglam@gmail.com']::text[], true),
  ('Be glitter', 'Extras (Glitter)', ARRAY['beglittereventos@gmail.com']::text[], true),
  ('Enjoy Glitter', 'Extras (Glitter)', ARRAY['jtorresgallesio@gmail.com']::text[], true),
  ('Smile', 'Extras (Foto imán)', ARRAY['smilefotoimanes@gmail.com']::text[], true),
  ('Baires', 'Extras (Cabina de fotos)', ARRAY['info@bairesphotobooth.com']::text[], true),
  ('La Cabina', 'Extras (Cabina de fotos)', ARRAY['lacabina.info@gmail.com']::text[], true),
  ('MG', 'Extras (Cotillón)', ARRAY['info@mgpartystore.com.ar']::text[], true),
  ('Hori', 'Extras (Cotillón)', ARRAY['horiconsultas@gmail.com']::text[], true),
  ('ZZ', 'Extras (Juegos)', ARRAY['info@zzproducciones.com.ar']::text[], true),
  ('Rental', 'Extras (Juegos)', ARRAY['alquiler.rg@gmail.com']::text[], true),
  ('Marciano', 'Extras (Juegos)', ARRAY['marcianoeventosok@gmail.com']::text[], true),
  ('Ozom', 'Extras (Cabina / Combi)', ARRAY['info@ozom.com.ar']::text[], true),
  ('OMG photobooth', 'Extras (Cabina de fotos)', ARRAY['posadafoto@gmail.com']::text[], true),
  ('PHOTO SMILE', 'Extras (Cabina de fotos)', ARRAY['photo.smile@hotmail.com']::text[], true),
  ('DUCK FOTO IMANES', 'Extras (Social Print)', ARRAY['duckfotoimanes@gmail.com']::text[], true),
  ('FOTO IMAN EN EL ACTO', 'Extras (Foto imán)', ARRAY['fotoimanenelacto@gmail.com']::text[], true),
  ('cabina foto selfie', 'Extras (Cabina de fotos)', ARRAY['lacabinaselfie@gmail.com']::text[], true),
  ('good show casino', 'Extras (Juegos)', ARRAY['goodshowcasino@hotmail.com']::text[], true),
  ('Nanas Montessori', 'Extras (Niños)', ARRAY['heymontessori@gmail.com']::text[], true),
  ('Insta Fest', 'Extras (Contenido)', ARRAY['hola@somosinstafest.com']::text[], true),
  ('Camara Rec', 'Extras (Contenido)', ARRAY['camararec.producciones@gmail.com']::text[], true),
  ('Siempre en fiestas', 'Detalles', ARRAY['infosiempreenfiestas@gmail.com', 'siempreenfiestas@gmail.com']::text[], true),
  ('EMME', 'Detalles', ARRAY['estudios.emme@gmail.com']::text[], true),
  ('Casa Sur Palermo', 'Hotelería', ARRAY['reservas@casasurpalermo.com']::text[], true),
  ('L´Hotel', 'Hotelería', ARRAY['info@lhotelpalermo.com']::text[], true),
  ('NH Palermo', 'Hotelería', ARRAY['nhpalermo@nh-hotels.com']::text[], true),
  ('Casa Sur Bellini', 'Hotelería', ARRAY['Reservas@casasurhotel.com']::text[], true),
  ('Mio Hotel', 'Hotelería', ARRAY['reservas@miobuenosaires.com']::text[], true),
  ('Hilton Pilar', 'Hotelería', ARRAY['reservations.pilar@hilton.com']::text[], true),
  ('Kos Pilar', 'Hotelería', ARRAY['reservas@kospilarhotel.com']::text[], true),
  ('Sheraton Pilar', 'Hotelería', ARRAY['telefonia@pilar.sheraton.com.ar']::text[], true),
  ('Carpas Argentinas', 'Carpas', ARRAY['ventas@carpasargentinas.com.ar']::text[], true),
  ('Tentikle', 'Carpas', ARRAY['info@carpasbeduinas.com']::text[], true),
  ('Sanitarios Top', 'Baños químicos', ARRAY['info@sanitariostop.com.ar']::text[], true),
  ('Sanitarios Premium', 'Baños químicos', ARRAY['info@sanitariospremium.com']::text[], true),
  ('Baños y eventos', 'Baños químicos', ARRAY['banosyeventos@hotmail.com']::text[], true);
