-- Seed inicial de proveedores (177 registros, cargados desde "Listado de proveedores (base de datos).xlsx")
-- Ejecutar UNA sola vez, después de add_providers_module.sql. Es idempotente por nombre+categoría:
-- si se corre dos veces, no duplica filas ya existentes con el mismo nombre y categoría.

insert into providers (name, category, emails, is_active)
select v.name, v.category, v.emails, true
from (
  values
  ('Estancia Ricardo Francisco', 'Locaciones', ARRAY['estanciaricardofrancisco@gmail.com']::text[]),
  ('Hostería El Cazador', 'Locaciones', ARRAY['info@hosteriaelcazador.com']::text[]),
  ('Dique Loreto', 'Locaciones', ARRAY['islaverde644@gmail.com']::text[]),
  ('El Abierto', 'Locaciones', ARRAY['pedro@mezclaeventos.com']::text[]),
  ('Darwin Tortugas', 'Locaciones', ARRAY['tortugas@somosdarwin.com.ar']::text[]),
  ('Darwin Buen Ayre', 'Locaciones', ARRAY['buenayre@somosdarwin.com.ar']::text[]),
  ('Estancia El Recuerdo', 'Locaciones', ARRAY['consultas@estanciaelrecuerdo.com']::text[]),
  ('Estancia Santa Elena', 'Locaciones', ARRAY['info@santaelenaeventos.com.ar']::text[]),
  ('5500 Figueroa', 'Locaciones', ARRAY['eventos@5500figueroa.com.ar']::text[]),
  ('Palacio Sans Souci', 'Locaciones', ARRAY['marinablanco@palaciosanssouci.com']::text[]),
  ('Quinta de Anchorena', 'Locaciones', ARRAY['nuva@nuvacatering.com']::text[]),
  ('Quinta de Bellavista', 'Locaciones', ARRAY['ventas@laquintabellavista.com.ar']::text[]),
  ('Espacio Pilar', 'Locaciones', ARRAY['sociales@espaciopilar.com.ar']::text[]),
  ('Espacio Márquez', 'Locaciones', ARRAY['sociales@espaciomarquez.com.ar']::text[]),
  ('Estancia Benquerencia', 'Locaciones', ARRAY['diego.natale@benquerencia.com.ar']::text[]),
  ('La Reserva', 'Locaciones', ARRAY['victoria.pinella@lareservaplaya.com']::text[]),
  ('Yatch PMO', 'Locaciones', ARRAY['planner@ycpm.info']::text[]),
  ('AAPolo', 'Locaciones', ARRAY['lorena@aapoloeventos.com']::text[]),
  ('Club Hípico Argentino', 'Locaciones', ARRAY['info@hipicoargentinoeventos.com.ar']::text[]),
  ('Espacio Tigre', 'Locaciones', ARRAY['sociales@espaciotigre.com.ar']::text[]),
  ('Torreon del Monje', 'Locaciones', ARRAY['eventos@torreondelmonjemdp.com']::text[]),
  ('Mar Eventos', 'Locaciones', ARRAY['info@mareventos.com.ar']::text[]),
  ('Cabo Largo', 'Locaciones', ARRAY['eventos@cabolargo.com.ar']::text[]),
  ('Playa Luna Roja', 'Locaciones', ARRAY['comercial@playalunaroja.com']::text[]),
  ('Maal Wines', 'Locaciones', ARRAY['gbiondo@maalwines.com']::text[]),
  ('Penedo Borges', 'Locaciones', ARRAY['eventos@penedoborges.com']::text[]),
  ('Bombal', 'Locaciones', ARRAY['info@bodegabombal.com']::text[]),
  ('La Morada', 'Locaciones', ARRAY['nayla@resolve.net.ar']::text[]),
  ('Huentala Wines', 'Locaciones', ARRAY['eventos@huentalawines.com']::text[]),
  ('Durigutti', 'Locaciones', ARRAY['turismo@durigutti.com']::text[]),
  ('Piso Tres', 'Locaciones', ARRAY['pedro@mezclaeventos.com']::text[]),
  ('La Escondida Olivos', 'Locaciones', ARRAY['maria@galindez.com.ar']::text[]),
  ('Bamba', 'Ambientación', ARRAY['vero@bambaambientaciones.com.ar', 'gime@bambaambientaciones.com.ar']::text[]),
  ('Luminis', 'Ambientación', ARRAY['luminisambientacion@gmail.com']::text[]),
  ('Dicha', 'Ambientación', ARRAY['contacto@dichambientacion.com']::text[]),
  ('Magnolia', 'Ambientación', ARRAY['ambientacionesmagnolia@gmail.com']::text[]),
  ('Chic to chic', 'Ambientación', ARRAY['info@chictochicambientaciones.com']::text[]),
  ('Genoveva Eventos', 'Ambientación', ARRAY['soniamorik@gmail.com']::text[]),
  ('Be', 'Ambientación', ARRAY['info@beambientaciones.com']::text[]),
  ('Amasb', 'Ambientación', ARRAY['luz@amasb.com.ar', 'clara@amasb.com.ar']::text[]),
  ('Cata Gallo', 'Ambientación', ARRAY['info@catagallo.com.ar']::text[]),
  ('Mercedes Courrage', 'Ambientación', ARRAY['mercedes@mercedescourreges.com.ar', 'martina@mercedescourreges.com.ar', 'catalina@mercedescourreges.com.ar']::text[]),
  ('Hermanas Carandoti', 'Ambientación', ARRAY['cande@hermanascaradonti.com', 'lola@hermanascaradonti.com']::text[]),
  ('By Felicity', 'Ambientación', ARRAY['agus.byfelicity@gmail.com', 'info.byfelicity@gmail.com']::text[]),
  ('Felicidad Rodante', 'Ambientación', ARRAY['produccion@felicidadrodante.com', 'virasseff@felicidadrodante.com', 'quiero@felicidadrodante.com']::text[]),
  ('Ambient Chic', 'Ambientación', ARRAY['info@ambientchic.com.ar']::text[]),
  ('Bar de eventos (BDE)', 'Barra', ARRAY['hola@bardeeventos.com', 'administracion@bardeeventos.com', 'logistica@bardeeventos.com']::text[]),
  ('Ehningen', 'Barra', ARRAY['info@barraparaeventos.com.ar']::text[]),
  ('CZ', 'Barra', ARRAY['info@czdrinks.com.ar']::text[]),
  ('Ramiro Ferreri (RF)', 'Barra', ARRAY['yo@ramiroferreri.com', 'ramiroferreri@gmail.com', 'rfpresupuestos1@gmail.com']::text[]),
  ('Holy', 'Barra', ARRAY['info@holychampagne.com.ar']::text[]),
  ('Tomate algo', 'Barra', ARRAY['info@tomatealgo.com.ar']::text[]),
  ('T-bar', 'Barra', ARRAY['hola@t-bar.com.ar']::text[]),
  ('Dream Factory / Drink Factory', 'Barra', ARRAY['info@drinkfactory.com.ar']::text[]),
  ('Fashion Drinks', 'Barra', ARRAY['info@fashiondrinks.com']::text[]),
  ('Julep de Inés de los Santos', 'Barra', ARRAY['info@julep.com.ar']::text[]),
  ('Softies', 'Catering', ARRAY['maria.fazzato@softiescatering.com']::text[]),
  ('Malcolm', 'Catering', ARRAY['info@malcolmcatering.com.ar']::text[]),
  ('Brazzi', 'Catering', ARRAY['info@brazzicatering.com.ar']::text[]),
  ('Fava', 'Catering', ARRAY['info@favacatering.com.ar', 'eugenia@favacatering.com.ar']::text[]),
  ('Expertos asadores', 'Catering', ARRAY['Info@expertosasadores.com.ar']::text[]),
  ('Galindez', 'Catering', ARRAY['maria@galindez.com.ar']::text[]),
  ('Guillen', 'Catering', ARRAY['eventos@guillencatering.com.ar']::text[]),
  ('Schuster', 'Catering', ARRAY['noelia.arbo@schuster-catering.com', 'nicolas.d@schuster-catering.com', 'info@schuster-catering.com']::text[]),
  ('Teist', 'Catering', ARRAY['ignacio@teist.com.ar']::text[]),
  ('Echague', 'Catering', ARRAY['mariaechaguecatering@gmail.com']::text[]),
  ('Tarelas', 'Catering', ARRAY['info@tarelas.com.ar']::text[]),
  ('Vivanco', 'Catering', ARRAY['ventas@vivanco.com.ar']::text[]),
  ('PCM', 'Catering', ARRAY['contacto@paracomertemejor.com.ar']::text[]),
  ('Quebracho y hierro', 'Catering', ARRAY['quebracho.hierro@gmail.com']::text[]),
  ('Art Catering', 'Catering', ARRAY['artventas@art-catering.com.ar']::text[]),
  ('Kiria Catering', 'Catering', ARRAY['info@kiria.com.ar']::text[]),
  ('Eat Catering', 'Catering', ARRAY['elena@eatcatering.com.ar', 'info@eatcatering.com.ar']::text[]),
  ('Los Petersen', 'Catering', ARRAY['catering@lospetersen.com']::text[]),
  ('Sucath David Catering', 'Catering', ARRAY['eventos@sucathdavid.com']::text[]),
  ('Griss', 'Técnica y Sonido', ARRAY['info@griss.com.ar']::text[]),
  ('Camisani', 'Técnica y Sonido', ARRAY['camisani.music@gmail.com', 'nicolas@camisani.com.ar']::text[]),
  ('Black Murray Smith', 'Técnica y Sonido', ARRAY['tomas@murrayblacksmith.com']::text[]),
  ('Sarapura', 'Técnica y Sonido', ARRAY['paula.gallardo@gruposarapura.com.ar', 'hola@gruposarapura.com.ar', 'flopyperego@sarapura.com']::text[]),
  ('Repila', 'Técnica y Sonido', ARRAY['sebamaidana@repila.com.ar', 'joseluis@repila.com.ar']::text[]),
  ('Juli Urristi', 'Técnica y Sonido', ARRAY['Juliurristidjs@gmail.com']::text[]),
  ('Trueba', 'Técnica y Sonido', ARRAY['eduardo@truebagroup.net', 'german@truebagroup.net']::text[]),
  ('Vidal Campos', 'Técnica y Sonido', ARRAY['comercial@vidalcampos.com.ar']::text[]),
  ('TM', 'Técnica y Sonido', ARRAY['bernardita@tmdj.com.ar']::text[]),
  ('Alejandro Massey', 'Técnica y Sonido', ARRAY['info@masseymusic.com.ar']::text[]),
  ('Leo Cragno', 'Técnica y Sonido', ARRAY['info@leocragno.com.ar']::text[]),
  ('Agus Faita', 'Otros Servicios', ARRAY['agus.faita@gmail.com']::text[]),
  ('Yami La Coquette', 'Otros Servicios', ARRAY['info@lacoquettenovias.com']::text[]),
  ('La China Buenos Aires', 'Otros Servicios', ARRAY['lachinabsas@gmail.com']::text[]),
  ('Mar make up', 'Otros Servicios', ARRAY['marmakeuphair@gmail.com']::text[]),
  ('Kari Loggia', 'Otros Servicios', ARRAY['karina.loggia@gmail.com']::text[]),
  ('Vero Fox', 'Otros Servicios', ARRAY['verofoxmakeup@gmail.com']::text[]),
  ('Luli Ruiz', 'Otros Servicios', ARRAY['luliruiz44@gmail.com']::text[]),
  ('Estudio Frumboli', 'Otros Servicios', ARRAY['estudio@bettinafrumboli.com']::text[]),
  ('Celeste Uria', 'Otros Servicios', ARRAY['CelesteUriaEstudio@gmail.com']::text[]),
  ('Laura Pintado', 'Otros Servicios', ARRAY['laupintadomakeup@gmail.com']::text[]),
  ('Paula Saez', 'Otros Servicios', ARRAY['paulasaezmakeup@gmail.com']::text[]),
  ('Rock That Makeup', 'Otros Servicios', ARRAY['mpaulicontreras@gmail.com']::text[]),
  ('Celeste Moreyra', 'Otros Servicios', ARRAY['mariaceleste.hairboutique@gmail.com']::text[]),
  ('Todaro - Dianez', 'Foto y Video', ARRAY['info@lucastodaro.com.ar', 'germandianez@gmail.com']::text[]),
  ('Dream Big', 'Foto y Video', ARRAY['contacto@dreambigestudio.com']::text[]),
  ('Alejandro Trotta', 'Foto y Video', ARRAY['aletrottavideografo@gmail.com']::text[]),
  ('Norman Parunov', 'Foto y Video', ARRAY['info@parunov.com.ar']::text[]),
  ('Pixel / Pixel Produxiones', 'Foto y Video', ARRAY['pixelProduxiones@hotmail.com']::text[]),
  ('Emi Gualdoni', 'Foto y Video', ARRAY['info@emiliagualdoni.com']::text[]),
  ('Filmyco', 'Foto y Video', ARRAY['info@filmyco.com']::text[]),
  ('Nico Panunnzio', 'Foto y Video', ARRAY['info@nicolaspannunzio.com.ar']::text[]),
  ('Bleu', 'Foto y Video', ARRAY['info@bleuestudio.com']::text[]),
  ('Mariano Brusa', 'Foto y Video', ARRAY['marianobrusa@marianobrusa.com.ar']::text[]),
  ('Pogo', 'Foto y Video', ARRAY['hola@pogoeventos.com']::text[]),
  ('Fede Petri', 'Foto y Video', ARRAY['info@fedepetri.com']::text[]),
  ('Finales Felices', 'Foto y Video', ARRAY['holafinalesfelices@gmail.com']::text[]),
  ('Paula Barcia', 'Foto y Video', ARRAY['info@paulacia.com']::text[]),
  ('Javier Belli', 'Foto y Video', ARRAY['belli_javier@hotmail.com']::text[]),
  ('Facundo Corral', 'Foto y Video', ARRAY['facundoncorral@gmail.com']::text[]),
  ('Gonzales Blanc', 'Foto y Video', ARRAY['estudiogonzalezblanc@gmail.com']::text[]),
  ('Punto Avi', 'Foto y Video', ARRAY['fabian@puntoavi.com.ar', 'info@punto-avi.com.ar']::text[]),
  ('Estudio ¾', 'Foto y Video', ARRAY['info@estudiotrescuartos.com.ar']::text[]),
  ('Estudio V', 'Foto y Video', ARRAY['hola@estudiov.net']::text[]),
  ('Alro Producciones', 'Foto y Video', ARRAY['info@alro.com.ar']::text[]),
  ('Hobby Estudio Creativo', 'Foto y Video', ARRAY['infocapital@hobbystudiocreativo.com', 'info@hobbystudio.com']::text[]),
  ('La ceremonia', 'Otros Servicios', ARRAY['laceremoniareuniones@gmail.com']::text[]),
  ('Arturo', 'Otros Servicios', ARRAY['estudiobayala@hotmail.com']::text[]),
  ('Tu ceremonia', 'Otros Servicios', ARRAY['contacto@tuceremonia.com']::text[]),
  ('Bodas para el alma', 'Otros Servicios', ARRAY['bodasparalasalmas@gmail.com']::text[]),
  ('Charlie', 'Otros Servicios', ARRAY['tuoficiantedeceremonias@gmail.com']::text[]),
  ('Leandro Biasutto', 'Otros Servicios', ARRAY['leobiasutto@gmail.com']::text[]),
  ('Fabian Skornik', 'Otros Servicios', ARRAY['agustina@lamroth.org']::text[]),
  ('El Show de Andy', 'Shows', ARRAY['elshowdeandy@hotmail.com']::text[]),
  ('Sin Ensayo', 'Shows', ARRAY['SINENSAYO@hotmail.com.ar']::text[]),
  ('Cafecitos', 'Shows', ARRAY['veronica.cgastaldiproducciones@gmail.com']::text[]),
  ('China Mora', 'Shows', ARRAY['veronica.cgastaldiproducciones@gmail.com']::text[]),
  ('Bairez Jazz Quartet', 'Shows', ARRAY['bairesjazzquartet@gmail.com']::text[]),
  ('Cuerdas del Sur', 'Shows', ARRAY['cuerdasdelsureventos@gmail.com']::text[]),
  ('LNA', 'Shows', ARRAY['info@lnaeventos.com.ar']::text[]),
  ('Morris Brown', 'Shows', ARRAY['morris_brown6@hotmail.com']::text[]),
  ('Nina Vais', 'Shows', ARRAY['info@ninavais.com']::text[]),
  ('Fernando saxo', 'Shows', ARRAY['showdesaxo@hotmail.com']::text[]),
  ('Soy el violinista', 'Shows', ARRAY['soyelviolinista@gmail.com']::text[]),
  ('El beso del arbol', 'Shows', ARRAY['fedelbehnson@gmail.com']::text[]),
  ('Lets Party', 'Extras', ARRAY['hola@letspartyarg.com', 'letspartyarg@gmail.com']::text[]),
  ('Estacion Glam', 'Extras', ARRAY['estacionesglam@gmail.com']::text[]),
  ('Be glitter', 'Extras', ARRAY['beglittereventos@gmail.com']::text[]),
  ('Enjoy Glitter', 'Extras', ARRAY['jtorresgallesio@gmail.com']::text[]),
  ('Smile', 'Extras', ARRAY['smilefotoimanes@gmail.com']::text[]),
  ('Baires', 'Extras', ARRAY['info@bairesphotobooth.com']::text[]),
  ('La Cabina', 'Extras', ARRAY['lacabina.info@gmail.com']::text[]),
  ('MG', 'Extras', ARRAY['info@mgpartystore.com.ar']::text[]),
  ('Hori', 'Extras', ARRAY['horiconsultas@gmail.com']::text[]),
  ('ZZ', 'Extras', ARRAY['info@zzproducciones.com.ar']::text[]),
  ('Rental', 'Extras', ARRAY['alquiler.rg@gmail.com']::text[]),
  ('Marciano', 'Extras', ARRAY['marcianoeventosok@gmail.com']::text[]),
  ('Ozom', 'Extras', ARRAY['info@ozom.com.ar']::text[]),
  ('OMG photobooth', 'Extras', ARRAY['posadafoto@gmail.com']::text[]),
  ('PHOTO SMILE', 'Extras', ARRAY['photo.smile@hotmail.com']::text[]),
  ('DUCK FOTO IMANES', 'Extras', ARRAY['duckfotoimanes@gmail.com']::text[]),
  ('FOTO IMAN EN EL ACTO', 'Extras', ARRAY['fotoimanenelacto@gmail.com']::text[]),
  ('cabina foto selfie', 'Extras', ARRAY['lacabinaselfie@gmail.com']::text[]),
  ('good show casino', 'Extras', ARRAY['goodshowcasino@hotmail.com']::text[]),
  ('Nanas Montessori', 'Extras', ARRAY['heymontessori@gmail.com']::text[]),
  ('Insta Fest', 'Extras', ARRAY['hola@somosinstafest.com']::text[]),
  ('Camara Rec', 'Extras', ARRAY['camararec.producciones@gmail.com']::text[]),
  ('Siempre en fiestas', 'Otros Servicios', ARRAY['infosiempreenfiestas@gmail.com', 'siempreenfiestas@gmail.com']::text[]),
  ('EMME', 'Otros Servicios', ARRAY['estudios.emme@gmail.com']::text[]),
  ('Casa Sur Palermo', 'Otros Servicios', ARRAY['reservas@casasurpalermo.com']::text[]),
  ('L´Hotel', 'Otros Servicios', ARRAY['info@lhotelpalermo.com']::text[]),
  ('NH Palermo', 'Otros Servicios', ARRAY['nhpalermo@nh-hotels.com']::text[]),
  ('Casa Sur Bellini', 'Otros Servicios', ARRAY['Reservas@casasurhotel.com']::text[]),
  ('Mio Hotel', 'Otros Servicios', ARRAY['reservas@miobuenosaires.com']::text[]),
  ('Hilton Pilar', 'Otros Servicios', ARRAY['reservations.pilar@hilton.com']::text[]),
  ('Kos Pilar', 'Otros Servicios', ARRAY['reservas@kospilarhotel.com']::text[]),
  ('Sheraton Pilar', 'Otros Servicios', ARRAY['telefonia@pilar.sheraton.com.ar']::text[]),
  ('Carpas Argentinas', 'Otros Servicios', ARRAY['ventas@carpasargentinas.com.ar']::text[]),
  ('Tentikle', 'Otros Servicios', ARRAY['info@carpasbeduinas.com']::text[]),
  ('Sanitarios Top', 'Otros Servicios', ARRAY['info@sanitariostop.com.ar']::text[]),
  ('Sanitarios Premium', 'Otros Servicios', ARRAY['info@sanitariospremium.com']::text[]),
  ('Baños y eventos', 'Otros Servicios', ARRAY['banosyeventos@hotmail.com']::text[])
) as v(name, category, emails)
where not exists (
  select 1 from providers p
  where p.name = v.name and p.category = v.category
);
